//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.29 at 10:25:31 PM MSK 
//


package ru.seminar.homework.hw5.soap.soap_dto;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.seminar.homework.hw5.soap.soap_dto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetNextWaitingTaskRequest_QNAME = new QName("http://www.example.com/soap", "GetNextWaitingTaskRequest");
    private final static QName _GetNextWaitingTaskResponse_QNAME = new QName("http://www.example.com/soap", "GetNextWaitingTaskResponse");
    private final static QName _UpdateTaskStatusRequest_QNAME = new QName("http://www.example.com/soap", "UpdateTaskStatusRequest");
    private final static QName _UpdateTaskStatusResponse_QNAME = new QName("http://www.example.com/soap", "UpdateTaskStatusResponse");
    private final static QName _CreateTaskRequest_QNAME = new QName("http://www.example.com/soap", "CreateTaskRequest");
    private final static QName _CreateTaskResponse_QNAME = new QName("http://www.example.com/soap", "CreateTaskResponse");
    private final static QName _DeleteTaskRequest_QNAME = new QName("http://www.example.com/soap", "DeleteTaskRequest");
    private final static QName _DeleteTaskResponse_QNAME = new QName("http://www.example.com/soap", "DeleteTaskResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.seminar.homework.hw5.soap.soap_dto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TaskDto }
     * 
     */
    public TaskDto createTaskDto() {
        return new TaskDto();
    }

    /**
     * Create an instance of {@link GetNextWaitingTaskRequest }
     * 
     */
    public GetNextWaitingTaskRequest createGetNextWaitingTaskRequest() {
        return new GetNextWaitingTaskRequest();
    }

    /**
     * Create an instance of {@link GetNextWaitingTaskResponse }
     * 
     */
    public GetNextWaitingTaskResponse createGetNextWaitingTaskResponse() {
        return new GetNextWaitingTaskResponse();
    }

    /**
     * Create an instance of {@link UpdateTaskStatusRequest }
     * 
     */
    public UpdateTaskStatusRequest createUpdateTaskStatusRequest() {
        return new UpdateTaskStatusRequest();
    }

    /**
     * Create an instance of {@link UpdateTaskStatusResponse }
     * 
     */
    public UpdateTaskStatusResponse createUpdateTaskStatusResponse() {
        return new UpdateTaskStatusResponse();
    }

    /**
     * Create an instance of {@link CreateTaskRequest }
     * 
     */
    public CreateTaskRequest createCreateTaskRequest() {
        return new CreateTaskRequest();
    }

    /**
     * Create an instance of {@link CreateTaskResponse }
     * 
     */
    public CreateTaskResponse createCreateTaskResponse() {
        return new CreateTaskResponse();
    }

    /**
     * Create an instance of {@link DeleteTaskRequest }
     * 
     */
    public DeleteTaskRequest createDeleteTaskRequest() {
        return new DeleteTaskRequest();
    }

    /**
     * Create an instance of {@link DeleteTaskResponse }
     * 
     */
    public DeleteTaskResponse createDeleteTaskResponse() {
        return new DeleteTaskResponse();
    }

    /**
     * Create an instance of {@link TaskDto.Times }
     * 
     */
    public TaskDto.Times createTaskDtoTimes() {
        return new TaskDto.Times();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetNextWaitingTaskRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetNextWaitingTaskRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.example.com/soap", name = "GetNextWaitingTaskRequest")
    public JAXBElement<GetNextWaitingTaskRequest> createGetNextWaitingTaskRequest(GetNextWaitingTaskRequest value) {
        return new JAXBElement<GetNextWaitingTaskRequest>(_GetNextWaitingTaskRequest_QNAME, GetNextWaitingTaskRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetNextWaitingTaskResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetNextWaitingTaskResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.example.com/soap", name = "GetNextWaitingTaskResponse")
    public JAXBElement<GetNextWaitingTaskResponse> createGetNextWaitingTaskResponse(GetNextWaitingTaskResponse value) {
        return new JAXBElement<GetNextWaitingTaskResponse>(_GetNextWaitingTaskResponse_QNAME, GetNextWaitingTaskResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateTaskStatusRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UpdateTaskStatusRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.example.com/soap", name = "UpdateTaskStatusRequest")
    public JAXBElement<UpdateTaskStatusRequest> createUpdateTaskStatusRequest(UpdateTaskStatusRequest value) {
        return new JAXBElement<UpdateTaskStatusRequest>(_UpdateTaskStatusRequest_QNAME, UpdateTaskStatusRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateTaskStatusResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UpdateTaskStatusResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.example.com/soap", name = "UpdateTaskStatusResponse")
    public JAXBElement<UpdateTaskStatusResponse> createUpdateTaskStatusResponse(UpdateTaskStatusResponse value) {
        return new JAXBElement<UpdateTaskStatusResponse>(_UpdateTaskStatusResponse_QNAME, UpdateTaskStatusResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateTaskRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CreateTaskRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.example.com/soap", name = "CreateTaskRequest")
    public JAXBElement<CreateTaskRequest> createCreateTaskRequest(CreateTaskRequest value) {
        return new JAXBElement<CreateTaskRequest>(_CreateTaskRequest_QNAME, CreateTaskRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateTaskResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CreateTaskResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.example.com/soap", name = "CreateTaskResponse")
    public JAXBElement<CreateTaskResponse> createCreateTaskResponse(CreateTaskResponse value) {
        return new JAXBElement<CreateTaskResponse>(_CreateTaskResponse_QNAME, CreateTaskResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteTaskRequest }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DeleteTaskRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.example.com/soap", name = "DeleteTaskRequest")
    public JAXBElement<DeleteTaskRequest> createDeleteTaskRequest(DeleteTaskRequest value) {
        return new JAXBElement<DeleteTaskRequest>(_DeleteTaskRequest_QNAME, DeleteTaskRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteTaskResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DeleteTaskResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.example.com/soap", name = "DeleteTaskResponse")
    public JAXBElement<DeleteTaskResponse> createDeleteTaskResponse(DeleteTaskResponse value) {
        return new JAXBElement<DeleteTaskResponse>(_DeleteTaskResponse_QNAME, DeleteTaskResponse.class, null, value);
    }

}
