//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.29 at 10:25:31 PM MSK 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.example.com/soap", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.seminar.homework.hw5.soap.soap_dto;
